#!/bin/bash -e

mkdir -p /var/muondetector
useradd muonuser -g users -G users -s /usr/sbin/nologin -r -N -M -b /var/muondetector || echo "User already exists"
chown muonuser:users /var/muondetector
chmod g+w /var/muondetector
