#!/bin/bash -e

mkdir -p /var/muondetector
useradd muonuser -g users -G users -s /usr/sbin/nologin -r -N -M -b /var/muondetector || echo "User already exists"
chown muonuser:users /var/muondetector
chmod g+w /var/muondetector

echo "Before starting the daemon, edit /etc/muondetector/muondetector-daemon.cfg and setup a credential file.\nTo do this edit the file /usr/share/muondetector/muondetector-cluster-credentials and execute \n\tsudo runuser -u muonuser muondetector-cluster -s /usr/share/muondetector/muondetector-cluster-credentials\nIf you want to run this daemon as a local cluster, add the option run_local_cluster:b:true to /etc/muondetector/muondetector-cluster.cfg."
